apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
  name: drupal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-pvc
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
        volumeMounts:
        - name: drupal-data
          mountPath: " /data"
      containers:
      - image: drupal:8.6
        imagePullPolicy: IfNotPresent
        name: drupal
        volumeMounts:
        - name: 'drupal-data'
          mountPath: "/var/www/html/"
          subPath: "modules"
        - name: 'drupal-data'
          mountPath: "/var/www/html/profiles"
          subPath: "profiles"
        - name: 'drupal-data'
          mountPath: "/var/www/html/sites"
          subPath: "sites"
          readOnly: false
        - name: 'drupal-data'
          mountPath: "/var/www/html/themes"
          subPath: "themes"
      restartPolicy: Always
status: {}
