apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      containers:
      - image: drupal:8.6
        name: drupal
        volumeMounts:
        - mountPath: "/data"
          name: mysql-data
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        command: [ "/bin/bash", "-c" ], initContainer: Args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
           claimName: drupal-pvc
