apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-09T10:11:31Z"
  labels:
    app: drupal-mysql
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":3306,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-06-09T10:11:31Z"
  name: drupal-mysql
  namespace: default
  resourceVersion: "28183"
  selfLink: /api/v1/namespaces/default/services/drupal-mysql
  uid: f89726aa-60bb-4410-b055-6407f004b319
spec:
  clusterIP: 10.106.114.194
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: drupal-mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
